#!/usr/bin/env bash
# seed-catalog.sh — generate an idempotent Supabase seed migration from a CSV batch.
# Emits INSERT ... ON CONFLICT (<key>) DO NOTHING inside BEGIN;/COMMIT;.
# Dry-run by default (stdout). --write saves a dated file into supabase/migrations/.
# bash 3.2-safe. CSV input (header row). Override root with GILDED_ROOT.
set -euo pipefail

GILDED_ROOT="${GILDED_ROOT:-$HOME/GILDED-EDGE-ECOSYSTEM}"
VENTURE=""; TABLE=""; CONFLICT=""; FILE=""; WRITE=0

usage() {
  cat <<USAGE
Usage: seed-catalog.sh --venture <v> --table <t> --conflict <col> rows.csv [--write]
  --venture   edge-design-works | gilded-art-works
  --table     catalog_items | catalog_categories | artwork_registry
  --conflict  UNIQUE column to dedupe on (slug | sku | artwork_id)
  --write     save into ventures/<v>/supabase/migrations/ (default: stdout)
CSV: first row is a header of real column names for <table>.
Array cols (materials,colors,style_tags,suggested_rooms) use ; to separate values.
JSONB cols (dimensions,provenance,documents) hold raw JSON in the cell.
Env: GILDED_ROOT
USAGE
}
while [ $# -gt 0 ]; do
  case "$1" in
    --venture) VENTURE="${2:-}"; shift 2 ;;
    --table) TABLE="${2:-}"; shift 2 ;;
    --conflict) CONFLICT="${2:-}"; shift 2 ;;
    --write) WRITE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) FILE="$1"; shift ;;
  esac
done
[ -n "$VENTURE" ] && [ -n "$TABLE" ] && [ -n "$CONFLICT" ] && [ -n "$FILE" ] && [ -f "$FILE" ] || { usage; exit 2; }

# Column classes for casting.
ARRAY_COLS=" materials colors style_tags suggested_rooms "
INT_COLS=" price_cents sort_order year scan_count times_placed times_purchased "
BOOL_COLS=" is_featured is_active tamper_detected "
# JSONB is table-aware: `dimensions` is JSONB in catalog_items but plain TEXT in
# artwork_registry (where it holds e.g. "48 x 36 in"). Casting it ::jsonb there fails.
case "$TABLE" in
  catalog_items)      JSONB_COLS=" dimensions " ;;
  artwork_registry)   JSONB_COLS=" provenance documents " ;;
  *)                  JSONB_COLS=" dimensions provenance documents " ;;
esac

is_in() { case "$2" in *" $1 "*) return 0 ;; *) return 1 ;; esac }

# Read header into COLS array (bash 3.2: no mapfile).
HEADER="$(head -1 "$FILE")"
OLDIFS="$IFS"; IFS=','; set -- $HEADER; IFS="$OLDIFS"
COLS=""
for h in "$@"; do
  h="$(printf '%s' "$h" | sed -e 's/^[[:space:]"]*//' -e 's/[[:space:]"]*$//')"
  COLS="$COLS $h"
done
COLS="$(printf '%s' "$COLS" | sed 's/^ //')"

# SQL-escape a scalar: double single-quotes.
esc() { printf '%s' "$1" | sed "s/'/''/g"; }

# Render one cell to a SQL literal based on its column name.
render_cell() {
  col="$1"; raw="$2"
  # trim surrounding spaces/quotes
  val="$(printf '%s' "$raw" | sed -e 's/^[[:space:]"]*//' -e 's/[[:space:]"]*$//')"
  if [ -z "$val" ]; then printf 'NULL'; return; fi
  if is_in "$col" "$INT_COLS"; then printf '%s' "$val"; return; fi
  if is_in "$col" "$BOOL_COLS"; then printf '%s' "$val"; return; fi
  if is_in "$col" "$JSONB_COLS"; then printf "'%s'::jsonb" "$(esc "$val")"; return; fi
  if is_in "$col" "$ARRAY_COLS"; then
    # split on ';' -> ARRAY['a','b']
    out="ARRAY["; first=1
    OLDIFS="$IFS"; IFS=';'; set -- $val; IFS="$OLDIFS"
    for a in "$@"; do
      a="$(printf '%s' "$a" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
      [ -z "$a" ] && continue
      if [ $first -eq 1 ]; then first=0; else out="$out,"; fi
      out="$out'$(esc "$a")'"
    done
    out="$out]::text[]"
    printf '%s' "$out"; return
  fi
  printf "'%s'" "$(esc "$val")"
}

# Build VALUES rows. Simple CSV split (no embedded commas inside quoted cells);
# for complex JSON cells, prefer a one-column-per-line source or keep JSON comma-free.
NCOLS="$(printf '%s' "$HEADER" | awk -F',' '{print NF}')"
VALUES=""
ROWNUM=0
while IFS= read -r line; do
  ROWNUM=$((ROWNUM+1))
  [ $ROWNUM -eq 1 ] && continue                 # skip header
  [ -z "$line" ] && continue
  OLDIFS="$IFS"; IFS=','; set -- $line; IFS="$OLDIFS"
  i=1; rowsql="("; first=1
  for col in $COLS; do
    eval "cell=\${$i:-}"
    lit="$(render_cell "$col" "$cell")"
    if [ $first -eq 1 ]; then first=0; else rowsql="$rowsql, "; fi
    rowsql="$rowsql$lit"
    i=$((i+1))
  done
  rowsql="$rowsql)"
  if [ -z "$VALUES" ]; then VALUES="  $rowsql"; else VALUES="$VALUES,
  $rowsql"; fi
done < "$FILE"

[ -n "$VALUES" ] || { echo "ERROR: no data rows in $FILE" >&2; exit 1; }

COLLIST="$(printf '%s' "$COLS" | tr ' ' ',' | sed 's/,,*/,/g')"
STAMP="$(date +%Y%m%d)"
MIG_NAME="${STAMP}_seed_${TABLE}.sql"
MIG_DIR="$GILDED_ROOT/ventures/$VENTURE/supabase/migrations"
MIG_PATH="$MIG_DIR/$MIG_NAME"

SQL="-- ══════════════════════════════════════════════════════════════════
-- Seed: $TABLE ($VENTURE) — idempotent (ON CONFLICT ($CONFLICT) DO NOTHING)
-- Generated by catalog-seeder. Safe to re-run; a repeat is a no-op.
-- ══════════════════════════════════════════════════════════════════
BEGIN;

INSERT INTO $TABLE ($COLLIST)
VALUES
$VALUES
ON CONFLICT ($CONFLICT) DO NOTHING;

COMMIT;"

if [ "$WRITE" -eq 1 ]; then
  [ -d "$MIG_DIR" ] || { echo "ERROR: migrations dir not found: $MIG_DIR" >&2; exit 1; }
  [ -e "$MIG_PATH" ] && { echo "ERROR: refusing to overwrite $MIG_PATH" >&2; exit 1; }
  printf '%s\n' "$SQL" > "$MIG_PATH"
  echo "WROTE: $MIG_PATH" >&2
  echo "APPLY: supabase migration up   (or Supabase MCP apply_migration). Review first." >&2
else
  echo "===== DRY RUN — would write: $MIG_PATH ====="
  printf '%s\n' "$SQL"
  echo ""
  echo "(re-run with --write to save; nothing was written)"
fi
