#!/usr/bin/env bash
# generate_baseline.sh — fold a loose schema.sql into migrations/000_baseline.sql.
# DRY RUN by default; pass --apply to write the file.
# Usage: generate_baseline.sh <venture-repo-root> [--apply]
# Never touches production. Never deletes the original schema.sql.

set -o pipefail

REPO="${1:?usage: generate_baseline.sh <venture-repo-root> [--apply]}"
APPLY=0
[ "${2:-}" = "--apply" ] && APPLY=1

# Locate supabase dir
SUPA=""
for cand in "$REPO/supabase" "$REPO/app/supabase" "$REPO/platform/supabase"; do
  [ -d "$cand" ] && { SUPA="$cand"; break; }
done
[ -z "$SUPA" ] && SUPA=$(find "$REPO" -maxdepth 4 -type d -name supabase -not -path '*/node_modules/*' 2>/dev/null | head -1)
[ -z "$SUPA" ] && { echo "✗ no supabase/ directory under $REPO"; exit 1; }

MIG="$SUPA/migrations"

# Find the source of truth: schema.sql, or a FULL_SCHEMA file inside migrations.
SRC=""
for s in "$SUPA/schema.sql" "$SUPA/../schema.sql"; do
  [ -f "$s" ] && { SRC="$s"; break; }
done
if [ -z "$SRC" ]; then
  for f in "$MIG"/*FULL_SCHEMA*.sql "$MIG"/*full_schema*.sql; do
    [ -f "$f" ] && { SRC="$f"; break; }
  done
fi
[ -z "$SRC" ] && { echo "✗ no schema.sql or FULL_SCHEMA*.sql found — nothing to baseline"; exit 1; }

OUT="$MIG/000_baseline.sql"

if [ -f "$OUT" ]; then
  echo "✗ $OUT already exists — refusing to overwrite. Remove it first if you mean to regenerate."
  exit 1
fi

HEADER="-- ══════════════════════════════════════════════════════════════════
-- 000_baseline.sql  —  GENERATED by supabase-migration-guard skill
-- Source of truth folded into the migration replay path so 'supabase db reset'
-- can rebuild the database from scratch.
--   generated: $(date '+%Y-%m-%d %H:%M:%S')
--   from:      $(basename "$SRC")
-- Do NOT edit this file to make schema changes — add a new timestamped migration.
-- The original $(basename "$SRC") is kept for reference; stop treating it as canonical.
-- ══════════════════════════════════════════════════════════════════
"

echo "== generate_baseline =="
echo "source:   $SRC"
echo "target:   $OUT"
echo "mode:     $([ "$APPLY" -eq 1 ] && echo APPLY || echo 'DRY RUN (pass --apply to write)')"
echo ""

if [ "$APPLY" -eq 1 ]; then
  mkdir -p "$MIG"
  { printf '%s\n' "$HEADER"; cat "$SRC"; } > "$OUT"
  echo "✓ wrote $OUT ($(wc -l < "$OUT") lines)"
  echo "  next: run find_collisions.sh on $MIG — later migrations may now re-create baseline tables."
  echo "  note: the original $(basename "$SRC") was left in place on purpose."
else
  echo "-- would write header + body of $(basename "$SRC") to 000_baseline.sql --"
  printf '%s\n' "$HEADER"
  echo "... [ $(wc -l < "$SRC") lines of $(basename "$SRC") body ] ..."
  echo ""
  echo "(dry run — no file written. Re-run with --apply.)"
fi
