#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════
# new-migration.sh — scaffold an owner-scoped Supabase migration in the
# Gilded Edge house style (RLS on, 4 explicit policies, index, trigger).
#
# DRY-RUN BY DEFAULT: prints SQL to stdout. Pass --write to save the file
# into the venture's supabase/migrations/ directory.
#
# Usage:
#   new-migration.sh --venture gilded-art-works --table collections [--owner user_id]
#   new-migration.sh --venture lumier-studios/app --table saved_views --owner owner_id --write
#
# No exotic deps — pure bash. Read-only unless --write is given.
# ══════════════════════════════════════════════════════════════════
set -euo pipefail

VENTURE=""
TABLE=""
OWNER="user_id"
WRITE=0
ROOT="${GILDED_ROOT:-$HOME/GILDED-EDGE-ECOSYSTEM}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --venture) VENTURE="$2"; shift 2 ;;
    --table)   TABLE="$2";   shift 2 ;;
    --owner)   OWNER="$2";   shift 2 ;;
    --write)   WRITE=1;      shift ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$TABLE" ]]; then
  echo "ERROR: --table is required" >&2; exit 2
fi
# Basic identifier sanity (Postgres unquoted identifier).
if ! [[ "$TABLE" =~ ^[a-z_][a-z0-9_]*$ ]]; then
  echo "ERROR: --table must be snake_case [a-z0-9_]: '$TABLE'" >&2; exit 2
fi
if ! [[ "$OWNER" =~ ^[a-z_][a-z0-9_]*$ ]]; then
  echo "ERROR: --owner must be snake_case: '$OWNER'" >&2; exit 2
fi

DATE="$(date +%Y%m%d)"
FILENAME="${DATE}_create_${TABLE}.sql"

SQL="$(cat <<SQL
-- ══════════════════════════════════════════════════════════════════
-- ${VENTURE:-<venture>} — ${TABLE}
-- Generated by rls-migration-writer (review columns before applying).
-- ══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ${TABLE} (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ${OWNER}    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- TODO: add your columns here, e.g.
  name        TEXT NOT NULL,
  -- foo_id   UUID REFERENCES foo(id) ON DELETE CASCADE,   -- add index below if you filter on it
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_${TABLE}_${OWNER} ON ${TABLE}(${OWNER});
-- CREATE INDEX IF NOT EXISTS idx_${TABLE}_foo ON ${TABLE}(foo_id);   -- index FKs you filter on

-- RLS is mandatory. Service role bypasses it — no policy needed for API/webhook routes.
ALTER TABLE ${TABLE} ENABLE ROW LEVEL SECURITY;

-- SELECT: owner sees only their rows.
CREATE POLICY "${TABLE}_select_own" ON ${TABLE}
  FOR SELECT USING (auth.uid() = ${OWNER});

-- INSERT: the new row must belong to the caller. NEVER "WITH CHECK (true)".
CREATE POLICY "${TABLE}_insert_own" ON ${TABLE}
  FOR INSERT WITH CHECK (auth.uid() = ${OWNER});

-- UPDATE: owner edits their rows; WITH CHECK blocks reassigning ownership.
CREATE POLICY "${TABLE}_update_own" ON ${TABLE}
  FOR UPDATE USING (auth.uid() = ${OWNER})
             WITH CHECK (auth.uid() = ${OWNER});

-- DELETE: owner only.
CREATE POLICY "${TABLE}_delete_own" ON ${TABLE}
  FOR DELETE USING (auth.uid() = ${OWNER});

-- Auto-touch updated_at. Shared fn (CREATE OR REPLACE is idempotent across migrations).
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS \$\$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
\$\$ LANGUAGE plpgsql;

CREATE TRIGGER ${TABLE}_updated_at
  BEFORE UPDATE ON ${TABLE}
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
SQL
)"

if [[ "$WRITE" -eq 1 ]]; then
  if [[ -z "$VENTURE" ]]; then
    echo "ERROR: --write requires --venture" >&2; exit 2
  fi
  DEST_DIR="$ROOT/ventures/$VENTURE/supabase/migrations"
  if [[ ! -d "$DEST_DIR" ]]; then
    echo "ERROR: migrations dir not found: $DEST_DIR" >&2
    echo "       (check the --venture path; some apps nest under <venture>/app)" >&2
    exit 1
  fi
  DEST="$DEST_DIR/$FILENAME"
  if [[ -e "$DEST" ]]; then
    echo "ERROR: refusing to overwrite existing $DEST" >&2; exit 1
  fi
  printf '%s\n' "$SQL" > "$DEST"
  echo "Wrote $DEST" >&2
  echo "Next: fill in real columns/FKs, then verify with 'supabase db reset'." >&2
else
  printf '%s\n' "$SQL"
  echo "" >&2
  echo "# Dry-run only. Review, then re-run with --write --venture <name> to save as $FILENAME" >&2
fi
