#!/usr/bin/env bash
# scaffold-aria-tool.sh — emit a new aria-agent /api/<name>/route.ts in ARIA's
# house conventions. Dry-run by default (prints to stdout); --write to create.
# bash 3.2-safe: no associative arrays, no mapfile, no ${var^^}.

set -u

NAME=""
ACTIONS="run"
GEMINI=0
NOTIFY=0
LOG_TABLE=""
WRITE=0
FORCE=0
USE_ZOD=1
GILDED_ROOT="${GILDED_ROOT:-$HOME/GILDED-EDGE-ECOSYSTEM}"

while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --actions) ACTIONS="$2"; shift 2 ;;
    --gemini) GEMINI=1; shift ;;
    --notify) NOTIFY=1; shift ;;
    --log-table) LOG_TABLE="$2"; shift 2 ;;
    --write) WRITE=1; shift ;;
    --force) FORCE=1; shift ;;
    --no-zod) USE_ZOD=0; shift ;;
    --zod) USE_ZOD=1; shift ;;
    -h|--help)
      echo "Usage: scaffold-aria-tool.sh --name <kebab> [--actions a,b,c] [--gemini] [--notify] [--log-table t] [--no-zod] [--write] [--force]"
      exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[ -n "$NAME" ] || { echo "ERROR: --name is required" >&2; exit 1; }

# derive a PascalCase label for logs/comments
LABEL=$(printf '%s' "$NAME" | awk -F'[-_]' '{ for (i=1;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2); }')
ROUTE_DIR="$GILDED_ROOT/ventures/aria-agent/src/app/api/$NAME"
ROUTE_FILE="$ROUTE_DIR/route.ts"

# build imports
IMPORTS="import { NextRequest } from 'next/server';"
[ "$USE_ZOD" -eq 1 ] && IMPORTS="$IMPORTS
import { z } from 'zod';"
[ "$GEMINI" -eq 1 ] && IMPORTS="$IMPORTS
import { GoogleGenAI } from '@google/genai';"
[ "$NOTIFY" -eq 1 ] && IMPORTS="$IMPORTS
import { notifyARIA } from '@/lib/notify';"
if [ -n "$LOG_TABLE" ]; then
  IMPORTS="$IMPORTS
import { supabaseService } from '@/lib/supabase';"
fi

# build the action cases and the GET actions array
CASES=""
GET_ACTIONS=""
OLDIFS="$IFS"; IFS=','
for a in $ACTIONS; do
  a=$(printf '%s' "$a" | tr -d ' ')
  [ -n "$a" ] || continue
  GET_ACTIONS="$GET_ACTIONS'$a', "
  CASE_BODY="        // TODO: implement '$a'"
  if [ "$GEMINI" -eq 1 ]; then
    CASE_BODY="        const prompt = \`TODO build the prompt for '$a' from body\`;
        const response = await ai.models.generateContent({
          model: 'gemini-2.5-flash',
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          config: { temperature: 0.6, maxOutputTokens: 4096 },
        });
        const output = response.text ?? '';"
  fi
  LOG_BODY=""
  if [ -n "$LOG_TABLE" ]; then
    LOG_BODY="
        await supabaseService.from('$LOG_TABLE').insert({
          tool: '$NAME', action: '$a', ok: true, created_at: new Date().toISOString(),
        });"
  fi
  NOTIFY_BODY=""
  [ "$NOTIFY" -eq 1 ] && NOTIFY_BODY="
        await notifyARIA(\`🤖 *$LABEL* ran \\\`$a\\\`\`, { silent: true });"
  RESULT_FIELD="ok: true"
  [ "$GEMINI" -eq 1 ] && RESULT_FIELD="ok: true, output"
  CASES="$CASES
      case '$a': {
$CASE_BODY$LOG_BODY$NOTIFY_BODY
        return Response.json({ action: '$a', $RESULT_FIELD });
      }
"
done
IFS="$OLDIFS"
GET_ACTIONS=$(printf '%s' "$GET_ACTIONS" | sed 's/, $//')

# gemini client init (module scope)
GEMINI_INIT=""
[ "$GEMINI" -eq 1 ] && GEMINI_INIT="
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
"

# input validation block
if [ "$USE_ZOD" -eq 1 ]; then
  VALIDATE="    const Input = z.object({ action: z.string() }).passthrough();
    const parsed = Input.safeParse(await req.json());
    if (!parsed.success) {
      return Response.json({ error: 'Invalid input', detail: parsed.error.flatten() }, { status: 400 });
    }
    const body = parsed.data;
    const { action } = body;"
else
  VALIDATE="    const body = await req.json();
    if (!body || typeof body.action !== 'string') {
      return Response.json({ error: 'Invalid input: { action } required' }, { status: 400 });
    }
    const { action } = body;"
fi

# gemini key guard
KEY_GUARD=""
[ "$GEMINI" -eq 1 ] && KEY_GUARD="
    if (!process.env.GEMINI_API_KEY) {
      return Response.json({ error: 'GEMINI_API_KEY not configured' }, { status: 500 });
    }
"

read -r -d '' FILE <<EOF
$IMPORTS

/* ═══════════════════════════════════════════════════════════════════
   POST /api/$NAME — ARIA $LABEL tool
   { action } dispatch · house conventions (Response.json, GEMINI_API_KEY,
   @/lib/notify, @/lib/supabase). Generated by aria-tool-scaffold.
═══════════════════════════════════════════════════════════════════ */
$GEMINI_INIT
export async function POST(req: NextRequest) {
  try {
$VALIDATE
$KEY_GUARD
    switch (action) {
$CASES
      default:
        return Response.json(
          { error: \`Unknown action: \${action}\`, available: [$GET_ACTIONS] },
          { status: 400 }
        );
    }
  } catch (error) {
    console.error('[ARIA $LABEL] Error:', error);
    return Response.json(
      { error: error instanceof Error ? error.message : '$LABEL error' },
      { status: 500 }
    );
  }
}

export async function GET() {
  return Response.json({
    engine: 'ARIA $LABEL',
    actions: [$GET_ACTIONS],
  });
}
EOF

if [ "$WRITE" -eq 1 ]; then
  if [ -f "$ROUTE_FILE" ] && [ "$FORCE" -ne 1 ]; then
    echo "ERROR: $ROUTE_FILE exists. Use --force to overwrite." >&2
    exit 1
  fi
  mkdir -p "$ROUTE_DIR"
  printf '%s\n' "$FILE" > "$ROUTE_FILE"
  echo "Wrote $ROUTE_FILE"
  [ "$USE_ZOD" -eq 1 ] && echo "NOTE: aria-agent does not ship 'zod' — run: (cd $GILDED_ROOT/ventures/aria-agent && npm i zod)"
else
  echo "# DRY-RUN — would write $ROUTE_FILE"
  echo "# Re-run with --write to create it."
  echo "# ----------------------------------------------------------------"
  printf '%s\n' "$FILE"
  [ "$USE_ZOD" -eq 1 ] && echo "# NOTE: zod is not a dep of aria-agent yet — npm i zod (or pass --no-zod)."
fi
