#!/usr/bin/env bash
# scaffold-structured-call.sh — emit a key-safe, Zod-validated Gemini call.
# bash 3.2 safe. DRY-RUN by default: prints to stdout, writes nothing.
# Pass --write to actually create the file.
#
# Usage:
#   scaffold-structured-call.sh --name analyzeInvoice [--venture gilded-form-works] [--write]
set -eu

NAME=""
VENTURE=""
WRITE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --name)    NAME="${2:-}"; shift 2 ;;
    --venture) VENTURE="${2:-}"; shift 2 ;;
    --write)   WRITE=1; shift ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$NAME" ]; then
  echo "ERROR: --name is required (e.g. --name analyzeInvoice)" >&2
  exit 2
fi

# PascalCase for the schema/type names from the camelCase function name.
PASCAL="$(printf '%s' "$NAME" | awk '{ print toupper(substr($0,1,1)) substr($0,2) }')"

read -r -d '' TEMPLATE <<EOF || true
/**
 * ${NAME}() — generated by gemini-structured-output.
 * Venture: ${VENTURE:-<set --venture>}
 *
 * REMINDER: the SDK + GEMINI_API_KEY must stay server-side. This file is the
 * CLIENT half; it only posts to the venture's proxy. Wire \`callProxy\` to the
 * venture's existing proxy (proxyGenerateContent / fetch('/api/...') /
 * supabase.functions.invoke('gemini-proxy')). Do NOT import @google/genai here.
 */
import { z } from 'zod';
import { structured, extractJson } from './structured-call'; // from skill assets/

export const ${PASCAL}Schema = z.object({
  // TODO: mark every field the UI dereferences as required (no .optional()).
  summary: z.string().default(''),
  score: z.number().min(0).max(100).default(0),
});
export type ${PASCAL} = z.infer<typeof ${PASCAL}Schema>;

const ${PASCAL}_FALLBACK: ${PASCAL} = { summary: 'Analysis unavailable.', score: 0 };

const responseSchema = {
  type: 'OBJECT',
  properties: {
    summary: { type: 'STRING' },
    score: { type: 'INTEGER', description: '0-100' },
  },
  required: ['summary', 'score'],
};

export async function ${NAME}(input: string): Promise<${PASCAL}> {
  return structured(
    ${PASCAL}Schema,
    async (repairHint) => {
      const prompt = repairHint ? input + '\\n\\n' + repairHint : input;
      // TODO: replace with the venture's proxy call. Must return raw model TEXT.
      const res = await callProxy('gemini-2.5-flash', prompt, {
        responseMimeType: 'application/json',
        responseSchema,
      });
      return res.text; // @google/genai => property; @google/generative-ai => res.text()
    },
    ${PASCAL}_FALLBACK,
  );
}

// Placeholder — delete once wired to the real proxy client.
declare function callProxy(model: string, prompt: string, config: unknown): Promise<{ text: string }>;
EOF

OUT="services/${NAME}.ts"

echo "== gemini-structured-output scaffold =="
echo "name:    ${NAME}"
echo "venture: ${VENTURE:-<unset>}"
echo "target:  ${OUT}"
echo "mode:    $([ "$WRITE" -eq 1 ] && echo WRITE || echo DRY-RUN)"
echo "----------------------------------------"
printf '%s\n' "$TEMPLATE"

if [ "$WRITE" -eq 1 ]; then
  if [ -e "$OUT" ]; then
    echo "REFUSING to overwrite existing $OUT" >&2
    exit 1
  fi
  mkdir -p "$(dirname "$OUT")"
  printf '%s\n' "$TEMPLATE" > "$OUT"
  echo "----------------------------------------"
  echo "WROTE $OUT"
else
  echo "----------------------------------------"
  echo "(dry-run) re-run with --write to create $OUT"
fi
